version: '3'
services:
  postgres:
    image: mdillon/postgis:9.6
    restart: always
    # Set port to non-standard value to not use Travis CI Postgres server.
    command: postgres -p 5434

  django:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    command: /codewof/codewof/docker-development-entrypoint.sh
    volumes:
      - .:/codewof
    environment:
      - PORT=8080
      - USE_DOCKER=yes
      - DATABASE_URL=postgres://postgres@postgres:5434/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - INCLUDE_INCONTEXT_L10N=False
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    volumes:
      - ./codewof/:/app/
      - /app/node_modules
    depends_on:
      - django
    ports:
      - "83:80"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"
